language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get install -y python-software-properties
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install -y gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
- gem install scss-lint
script: gulp
deploy:
  provider: heroku
  buildpack: ruby
  skip_cleanup: true
  api_key:
    secure: lGekh0GU9c0mszl1xKMMXMDBTm8RgC/qn5JKpinEhXFqbNuYgO5FRGB+T1sRCuGXGOE8+V+k8YONyF210n9rOx1j/+akwADKbTs2viIM3H0LqQq7yOaFyF9MSMjSzEm8tDeIHmPrehiHTWqL9sG0c/GItcMJ3h9GwqyMKV1WV0Q=
  app: bigtrip
  on:
    repo: tylergaw/bigtrip
