language: node_js
node_js:
  - '0.10'
before_install:
  - gem install sass -v '>= 3.4.0'
  - gem install scss-lint -v '>= 0.29.0'
before_script:
  - npm install -g bower@1.3.x
  - bower install
script: gulp
